global_settings:
  log_level: INFO
  dry_run: true

file_filters:
  min_height: 600
  min_width: 600
  extensions:
    - jpg
    - jpeg
    - png
    - mp4
    - mov
    - mpg
    - wmv
    - avi
    - 3gp

action: move

input_folders:
  - path: data/input
    max_depth: 1

output_folder:
  base_path: "data/output"
  # Allowed template vars: year, month, day
  template: "{year}/{month}"
